<?php

define('APPLICATION_NAME', 'BiblioStages');
define('APPLICATION_URL', 'lecteur');
define('LOG_FILE_NAME', 'lecteur');
define('APPLICATION_VERSION', '2.4.1');
// define('URL_APPLICATION', 'http://localhost/lecteur');
define('URL_APPLICATION', 'http://basile.parent.free.fr/lecteur');
define('ABSOLUTE_PATH', '/lecteur/');

/*
DEFINE('DB_HOST', 'sql.free.fr');
DEFINE('DB_USER', 'basile.parent');
DEFINE('DB_PASSWORD', 'jiraigum');
DEFINE('DB_NAME', '');
*/

DEFINE('DB_HOST', 'localhost');
DEFINE('DB_USER', 'root');
DEFINE('DB_PASSWORD', '');
DEFINE('DB_NAME', 'stages');


DEFINE('ENCODING_STATE_WAITING', 1);
DEFINE('ENCODING_STATE_RUNNING', 2);
DEFINE('ENCODING_STATE_ENDED_WITH_ERRORS', 5);
DEFINE('ENCODING_STATE_ENDED_OK', 6);


DEFINE('PATH_RAW_FILE', 'ressources'.DIRECTORY_SEPARATOR.'raw_videos');
DEFINE('PATH_RAW_FILE_BIN', 'ressources'.DIRECTORY_SEPARATOR.'raw_videos_bin');
DEFINE('PATH_CONVERTED_FILE', 'ressources'.DIRECTORY_SEPARATOR.'video_traitees');
DEFINE('PATH_FFMPEG', 'ressources'.DIRECTORY_SEPARATOR.'ffmpeg.exe');
DEFINE('PATH_THUMBNAIL', 'ressources'.DIRECTORY_SEPARATOR.'thumbnails');
DEFINE('PATH_LOG_FOLDER', 'logs');


DEFINE('VIDEO_TYPE_COURS', 'COURS');
DEFINE('VIDEO_TYPE_STAGE', 'STAGE');
DEFINE('VIDEO_TYPE_FORMATION', 'FORMATION');
DEFINE('VIDEO_TYPE_SHOW', 'SHOW');
DEFINE('VIDEO_TYPE_ROUTINE', 'ROUTINE');
DEFINE('VIDEO_TYPE_LIBRE', 'LIBRE');
DEFINE('VIDEO_TYPE_INTERNET_TIPS', 'IE_TIPS');
DEFINE('VIDEO_TYPE_INTERNET_SHOWS', 'IE_SHOWS');

$VIDEO_TYPES = array(
		VIDEO_TYPE_COURS => 'Cours',
		VIDEO_TYPE_STAGE => 'Stage',
		VIDEO_TYPE_FORMATION => 'Formation',
		VIDEO_TYPE_SHOW => 'Show',
		VIDEO_TYPE_ROUTINE => 'Routine',
		VIDEO_TYPE_LIBRE => 'Libre',
		VIDEO_TYPE_INTERNET_TIPS => 'Internet - Tips',
		VIDEO_TYPE_INTERNET_SHOWS => 'Internet - Shows' );

DEFINE('NIVEAU_INITIATION', '10_INITIATION');
DEFINE('NIVEAU_DEBUTANT', '20_DEBUTANT');
DEFINE('NIVEAU_INTER', '30_INTER');
DEFINE('NIVEAU_INTER_PLUS', '40_INTER_PLUS');
DEFINE('NIVEAU_AVANCE', '50_AVANCE');
DEFINE('NIVEAU_COMPETITION', '60_COMPETITION');

$NIVEAUX = array(
		NIVEAU_INITIATION => 'Initiation',
		NIVEAU_DEBUTANT => 'Débutant',
		NIVEAU_INTER => 'Inter',
		NIVEAU_INTER_PLUS => 'Inter+',
		NIVEAU_AVANCE => 'Avancé',
		NIVEAU_COMPETITION => 'Compétition');


DEFINE('DROIT_CONSULT', 'CONSULT');
DEFINE('DROIT_UPLOAD', 'UPLOAD');
DEFINE('DROIT_EDIT_VIDEO', 'EDIT_VIDEO');
DEFINE('DROIT_ADMIN', 'ADMIN');
DEFINE('DROIT_PLAY_VIDEO', 'PLAY_VIDEO');
DEFINE('DROIT_CAN_BOOKMARK', 'CAN_BOOKMARK');
DEFINE('DROIT_CONSULT_PARTAGE', 'CONSULT_PARTAGE');
DEFINE('DROIT_ACTION_ALLOW_USER', 'ACTION_ALLOW_USER');
DEFINE('DROIT_ACTION_ALLOW_PROFILE', 'ACTION_ALLOW_PROFILE');
DEFINE('DROIT_ACTION_AFFECT_TAG', 'ACTION_AFFECT_TAG');
DEFINE('DROIT_ACTION_USE_PLAYLIST', 'ACTION_USE_PLAYLIST');
DEFINE('DROIT_MANAGE_PLAYLIST', 'MANAGE_PLAYLIST');
DEFINE('DROIT_LOG_AS', 'LOG_AS');


$DROIT_ACTION = array(DROIT_ACTION_ALLOW_USER, 
	DROIT_ACTION_ALLOW_PROFILE, 
	DROIT_ACTION_AFFECT_TAG,
	DROIT_ACTION_USE_PLAYLIST);


DEFINE('DEFAULT_EVENT_COLOR_ID', -1);
DEFINE('DEFAULT_EVENT_COLOR_LIBELLE', "Default color");
DEFINE('DEFAULT_EVENT_COLOR_CSS', 'accordeon-blue');

DEFINE('NO_EVENT_VIDEO_ID', -1);


?>